// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVl8-Pu8x_k7GT3WkIWqNZEsL1210y7c',
    appId: '1:97713662380:web:823db4470e1b5aa7b6f209',
    messagingSenderId: '97713662380',
    projectId: 'final-project-7defe',
    authDomain: 'final-project-7defe.firebaseapp.com',
    storageBucket: 'final-project-7defe.appspot.com',
    measurementId: 'G-MF6MXKFLQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsooM_UeJI-jl6b3lYCFi_JXIfHzExOuc',
    appId: '1:97713662380:android:4e760f03d1a91084b6f209',
    messagingSenderId: '97713662380',
    projectId: 'final-project-7defe',
    storageBucket: 'final-project-7defe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWYUGKFjqz7zEJwAmLlbT5PLuHeom1TE',
    appId: '1:97713662380:ios:911f20c867a2c249b6f209',
    messagingSenderId: '97713662380',
    projectId: 'final-project-7defe',
    storageBucket: 'final-project-7defe.appspot.com',
    iosClientId: '97713662380-j4ovmiser9vr2vkdj8sbnun930trv7jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWYUGKFjqz7zEJwAmLlbT5PLuHeom1TE',
    appId: '1:97713662380:ios:911f20c867a2c249b6f209',
    messagingSenderId: '97713662380',
    projectId: 'final-project-7defe',
    storageBucket: 'final-project-7defe.appspot.com',
    iosClientId: '97713662380-j4ovmiser9vr2vkdj8sbnun930trv7jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
